# Generated by Django 5.2.7 on 2025-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('chef', 'Chef'), ('admin', 'Admin')], max_length=10),
        ),
    ]
