# Generated by Django 5.2.7 on 2025-10-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_chef_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='imagge',
            new_name='image',
        ),
    ]
